language: cpp
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      - g++
      - cmake
      - boost

install:
  - sudo apt-get install -y libncurses5-dev

before_script:
  - cmake -Bbuild -H.

script:
  - cmake --build build/ --target all
  - cd build/ && ctest
